- get.php
Windows 10 App Essentials 21.01 is a major release that will require NVDA 2020.3 or later. It is also the last version to support Windows 10 Version 1909 (November 2019 Update/build 18363).
* Name: Windows 10 App Essentials
* Author: Joseph Lee, Derek Rimer and contributors
* Repo: https://github.com/josephsl/wintenapps
* Branch: stable (tag: 21.01)
* NVDA compatibility: 2020.3 and later
Changelog:
* NVDA 2020.3 or later is required.
* Various workarounds that were included with the add-on are now part of NVDA. These include reading Open With dialog content and better recognition of progressive web apps (PWA's) hosted by WWA Host process.
* Removed app modules for Open With dialog and WWA Host process.
* UIA help text (description change) property event is now …
> Windows 10 App Essentials 21.01

- get.php
Hi,
A companion pull request was submitted to add-on store submission repo hosted by NV Access:
* Name: Windows 10 App Essentials
* Version: 21.02
* Author: Joseph Lee, Derek Riemer and contributors
* Repo: https://github.com/josephsl/wintenapps
* Release branch: stable (tag: 21.02)
* NVDA compatibility: 2020.3 and later
Changelog: requires Windows 10 Version 2004 (May 2020 Update/build 19041), initial support for updated emoji panel in Insider Preview build 21296 and later.
Thanks.
> Windows 10 App Essentials 21.02

- get.php
* Name: StationPlaylist
* Author: Geoff Shang, Joseph Lee and contributors
* Repo: https://github.com/josephsl/stationPlaylist
* Version: 21.02
* Branch: 21.01.x (no tag)
* NVDA compatibility: 2020.3 or later
Changelog:
* Columns explorer commands and encoder status announcements will work properly if NVDA is started while focused on a track in Studio or encoders. This is applicable to NVDA 2020.4 or later.
* NVDA will no longer fial to save encoder settins after errors are encountered when loading settings at startup.
Note: version 21.02 backports critical bug fixes from upcoming 21.03 release.
Thanks.
> StationPlaylist 21.02

- get.php
- Add-on name: Weather_Plus
- Version: 7.7
- Warning: Last NVDA version tested: 2021.2
Note: I have explained to the author that changes maybe required before accepting this PR. I'm not sure about your criteria here, since NVDA 2021.2 is not released and backward compatibility version number will be changed before the first beta of NVDA 2021, so we don't need to update this number for now.
🤔
> Update Weather_Plus to 7.7

- get.php
Hi,
This add-on was reviewed in 2019 and now being registered for community distribution (ap9ologies for this lateness)...
This add-on allows users to select update chanel for NVDA screen reader without having to visit snapsthos page.
* Name: Update Channel Selector
* Author: jose Manuel Delicado
* Repo: https://github.com/nvda-es/updateChannel
* Version: 1.0.2
* Add-on update channel: stable
* NVDA compatibility: 2019.1 to 2020.4
* Add-on files update key: updchannelselect
* Basic review reference thread: https://nvda-addons.groups.io/g/nvda-addons/topic/34396512#10965
* Basic review: license and copyright/pass, documentation/pass, security/pass, user experience/pass
Thanks.
> Update Channel Selector initial (1.0.2) by Jose Manuel Delicado)

- get.php
This add-on allows the NVDA screen reader to connect to the Internet through one or more proxy servers. To make it possible, it applies various patches to the standard Python library or modifies certain environment variables, depending on the chosen configuration. You will be able to update NVDA and their add-ons automatically from your corporate environment and even perform remote sessions, provided that your organization proxy server allows it.
* Name: proxy support
* Author: José Manuel Delicado
* Repo: https://github.com/nvda-es/nvda-proxy-support
* Version: 1.0.2
* Add-on update channel: stable
* NVDA compatibility: 2019.3 to 2020.4
* Add-on files update key: nvdaproxy
* Basic review reference thread: https://nvda-addons.groups.io/g/nvda-addons/topic/79148064
* Basic review: license …
> Proxy support 1.0.2 (initial)

- get.php
* Name: Windows 10 App Essentials
* Author: Joseph Lee, Derek Riemer and contributors
* Repo: https://github.com/josephsl/wintenapps
* Version: 21.06
* NVDA compatibility; 2020.4 and beyond
* Windows compatibility: 10.0.19041 and later
* SHA 256: 169ac65c46f72978a6a76c0cf41d05961720a8041b5902623ab655a459bb8e7b
Changelog:
* NVDA 2020.4 or later is required.
* The following UIA events were renamed to make them consistent with actual UI Automation event names: drag target enter to drop target enter, drag target leave to drop target leave, drag target dropped to drop target dropped.
* Modern keyboard: in build 21300 and later, with focus mode active from places such as web browsers, NVDA will no longer announce blank when using the arrow keys to navigate among emojis. …
> Windows 10 App Essentials 21.06

- get.php
This pull request   updates link to the WinWizard to the version 5.03. which is compatible with NVDA  2021.1.
https://github.com/lukaszgo1/winWizard/tree/V5.0.3
No code changes aside from updating last tested NVDA version were necessary however I've updated the readme to note that the new release is compatible with 2021.1 and I would be grateful if it could be updated on the website. Alternatively I'm  happy to do it myself if I'm told how to do so.
> Update WinWizard to version 5.0.3

- get.php
- Add-on name: Weather_Plus
- Version: 8.1
- url: https://www.nvda.it/weather-plus/
Pull request created on behalf of the author:
https://nvda-addons.groups.io/g/nvda-addons/message/15862
> Update Weather_Plus to 8.1

- get.php
Note: Windows 10 App Essentials will be renamed to Windows App Essentials soon.
* Name: Windows 10 App Essentials
* Author: Joseph Lee and contributors
* Repo: https://github.com/josephsl/wintenapps
* Version: 21.06.1
* NVDA compatibility: 2020.4 to 2021.1
* SHA256: 2deb6a91f96945bff17717039cb62e4a93d1d4fcc04666bde468602263e6d250
Changelog: Windows 11 Insider Preview (build 22000) is being tested by Insiders. It might be possible that people might install stable versions of this add-on in Windows 11, therefore a warning dialog was added. If the user chooses to install the add-on on Windows 11 despite warnings, a Windows 11 detection message will be logged every time NVDA starts. The warning dialog and the detection message will be gone once Windows 11 is released …
> Windows 10 App Essentials 21.06.1

- get.php
- Version: 21.08
- NVDA compatibility: 2020.4 and beyond
- Sha256: 67a338c7e4c2766fbef52eeaf09412f50a265b934b570686f70408d9477d2b13
* Initial support for Windows 10 Version 21H2 (Second 2021 Update), unofficial support for Windows Server 2022. These two releases have different build numbers.
* Requires Windows 10 Version 20H2 or later.
* Experimental support for Windows 11, not to be confused with Windows 10 Version 21H2.
* Windows Search (formerly classic Cortana) and modern keyboard app modules were renamed to reflect executable names for these apps in Version 2004 and later.
* Removed app module for combined Mail and Calendar …
> Windows App Essentials 21.08

- get.php
- Repo: https://github.com/ruifontes/Weather_Plus
- Version: 8.4
- Update: Stable
- Fixed copy function of partial text selection using control + c, and enabled the home, end and pageup keys, pagedown in enabled windows.
- Correct response pressure in mmHg.
- Update Weather_Plus to version 8.4;
- The change log is only from the last version;
- Change repository to:
https://github.com/ruifontes/Weather_Plus
by request of author, Adriano Barbieri
> Update Weather_Plus to version 8.4

- get.php
- Version: 21.11
- NVDA compatibility: 2021.2 and later
- Sha256: 27612d0267273fd30b45536cbeb397a795cbe81666c594e907cbea0a1ecff6e1
- Partially removed the ability to recognize additional dialogs as recent Windows and app updates improve NVDA's ability to detect dialogs without help from the add-on. Dialogs with UIA class names included in NVDA will still be detected.
- The debug log prefix was changed from "W10" to "winapps" to reflect the renamed add-on.
- It is no longer required to enable report object position information option from NVDA's object presentation settings to be notified about suggestion count when searching in various …
> Windows App Essentials 21.11

- get.php
- Author: Joseph Lee
- Version: 22.01
- NVDA compatibility: 2021.2 and later
- Sha256: 644a370d40678c1699f80a7ad90b3dbc6f652cbe7f2a8328743aa38a871e3d3f
- Transferred layout invalidated event tracking and logging to Event Tracker add-on.
- The following UIA events are no longer tracked and logged due to lack of useful information: drag start, drag cancel, drop target enter, drop target leave.
- XAML heading recognition is deprecated and will be removed in a future release as it caused problems in apps such as Calculator and Settings.
- Removed app modules for File Explorer and Microsoft Store as Store version 2 (Windows 10/11) provides better support for download progress announcements …
> Windows App Essentials 22.01

- get.php
- Name: Access8Math
- Author: Tseng Woody
- Repo: https://github.com/tsengwoody/Access8Math
- Version: 3.2
- NVDA compatibility: 2019.3~2021.3.1
- New feature "`" to separate data blocks, the blocks enclosed by "`" are AsciiMath data
- New feature editing-shortcut for browse navigation mode cut (ctrl+x), copy (ctrl+c), paste (ctrl+v), delete (delete/back space)
- New feature moving-shortcut for browse navigation mode move between interactive data blocks (tab), move between AsciiMath data blocks (a)
- Change move cursor way in browse navigation mode - move cursor way with up, down, left and right arrow keys and read out the contents of the data block after the movement.
- When the cursor moves in the browse navigation mode, the math data block will read the …
> Access8Math 3.2

- get.php
- Name: Beep keyboard.
- Author: David CM
- Repo: https://github.com/davidacm/beepKeyboard
- Version: 1.7
- NVDA compatibility: from 2018.3 to 2021.3.1
- updated manifest to support NVDA 2021.3.1.
- updated readme
- added a check to disable toggle beeping if toggle keys in ease of access is enabled, since this feature can be enabled on the system but doesn't work very well for NVDA with laptop keyboard layout.
> updated beepKeyboard to 1.7 version.

- get.php
- Name: Sound Splitter
- Author: Joseph Lee
- Repo: https://github.com/josephsl/soundsplitter
- Version: 22.02
- NVDA compatibility: 2019.3 and later
- Sha256: becd01dea8c51f35896ca13c9b8c725d527c72fc5bc4201139d8d01f14622d8a
- Initial release based on Tony's Enhancements.
Sound Splitter code was originally part of Tony's Enhancements and was split with blessing from Tony Malykh.
> Sound Splitter 22.02 (initial release)

- get.php
- Author: Joseph Lee
- Version: 22.02
- NVDA compatibility: 2021.2 and later
- Sha256: dcd164b393845c9da8c34d4b8003ef6bac1e345d465142fd6ad05916c97d586f
- Windows 10: Requires Version 21H1 or later.
- In Windows 11, microphone mute status is announced from anywhere when Windows+Alt+K is pressed.
- Notepad (Windows 11 preview): Provided that status bar is checked from View menu, NVDA will no longer announce status bar information such as line number from places other than documetn edit window.
> Windows App Essentials 22.02

- get.php
- Repo: https://github.com/ruifontes/Weather_Plus/
- Version: 8.7
- Added "en" folder missing in the documentation. 
- if the Copy the weather report and weather forecast, including city details to clipboard item is enabled, pressing nvda + alt + w will now also copy the date of the last update of the bulletin to the clipboard.
The author (Adriano Barbieri) has requested me to create this PR. Release information and changelog, including repo,  are copied from info sent privately by the author.
cc: @ruifontes
> Update Weather_Plus to 8.7, requested by author (Adriano Barbieri)

- readme.md
After a recent discussion on NVDA-addons list, I realized that a dev who is admittedly not as active as previously, did not seem to understand the process for updating get.php, even after a referral to https://addons.nvda-project.org/requirements.en.html.
After reading that file again myself, I thought that it was thin on specific details, for anyone not already familiar with the process.
Not being able to edit that file, I thought I would try to improve readme.md here in addonFiles, as it appears to be the basis for the requirements file.
* Re-wrote the "New Add-ons" section, to better elaborate the process for devs not used to using addonFiles.
* Added a subsection called "Get.php for New Add-ons", containing both notes about unique keys in get.php.
* Added a subsection called "Get.php …
> Expanded readme with more sections and details, to better explain the addonFiles process

- get.php
- Version: 22.03.1
- NVDA compatibility: 2021.3 and later
- Sha256: 4ac787aa0fe089a06d4cf17af6d20c82a26b8b07ee1f4bba3750c401c7957568
- NVDA 2021.3 or later is required, more so for security (NVDA 2021.3.3 is advised).
- Various features and fixes that were included with the add-on are now part of NVDA. These include announcing search suggestion count in apps such as Settings and Microsoft Store and "pane" no longer being announced when switching between apps in Windows 11.
- Installing and using the add-on on Windows Insider Preview builds between 20348 (Server 2022) and 22000 (Windows 11) is no longer supported.
- Removed the warning …
> Windows App Essentials 22.03.1

- get.php
- Version: 22.03.2
- NVDA compatibility: 2021.3 and later
- Sha256: 09cc8b0e9c811b79cd96b0b465d022ed184243eccb625a0d140ed39f0ce86e18
- NVDA will no longer repeat text output in Windows Terminal 1.12.10733 and later (this fix is applicable to NVDA 2021.3.x as 2022.1 resolves this).
> Windows App Essentials 22.03.2

- get.php
- Name: applicationDictionary
- Author: Rui Fontes <rui.fontes@tiflotecnia.com> and Ricardo Leonarczyk <ricardo.leonarczyk95@gmail.com> and colaboration of Cyrille Bougot
- Repo: https://github.com/ruifontes/applicationDictionary-
- Version: 2022.03.26
- NVDA compatibility: 2019.3 and beyond
- Compatibility changed to 2019.3 and beyond;
- Avoid duplication of "Application dictionary" submenu after reloading plugins;
- Thanks to Cyrille Bougot:
- Dictionaries created before migration to a separate directory are now moved there automatically
- Empty files are no longer created when opening dictionary dialog
- Empty files are no longer pointlesly kept in the config
- Make not check updates at startup as default.
Authorized, long time ago, to submitt it again to …
> New add-on applicationDictionary

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/FASTER_PR.md
Hi,
I created another template for PR.
In short, this presents a comment with a filled template as example, and then the blank template, to fill-in without you have to delete info and parenthesis around.
I use gh (github-cli), so I don't know if it could be good for web interface too... In this branch should be selectable as alternative to default, but I was not able to test it, unfortunately (I suspect it can be selected only when placed in master branch).
Please, consider this small improvement.
> Alternative faster PR template

- get.php
- Name: Screenshots Wizard
- Author: Javi Dominguez
- Repo: https://github.com/javidominguez/screenshots/
- Version: 1.0
- NVDA compatibility: 2021.2 and beyond
- New addon
- 2022.1 compatible
This add-on provides a wizard to take screenshots of the entire screen or specific areas such as objects, windows, etc. It is activated by the _print screen_ key which on standard keyboards is usually the first of the group of three to the right of F12. If you prefer to use another, it can be configured in the NVDA preferences, input gestures.
When the wizard is invoked, a virtual rectangle is created around the object with focus and a layer of keyboard commands is activated. See [documentation](https://github.com/javidominguez/screenshots/raw/95c7162db7d706de1c7a806fc6ace931 …
> New addon Screenshots Wizard

- get.php
- Name: Access8Math
- Author: Tseng Woody
- Repo: https://github.com/tsengwoody/Access8Math
- Version: 3.3
- NVDA compatibility: 2019.3~2022.1
*	Add built-in editor using traditional editing area because of windows 11 changed to UIA editing area
*	built-in editor new/open/save feature
*	Access8Math language initial setting is based on NVDA language setting
*	Improved speech and braille display in virtual menus
*	Compatibility with NVDA 2022.1
*	Fixed marked menu cannot open when document is empty
*	Fixed translate LaTeX/AsciiMath feature
*	Fixed HTML document rendering problem when HTML document display setting choice text option
> Access8Math 3.3

- get.php
- Repo: https://github.com/ruifontes/weather_plus
- Version: 8.9
- Complement in secure screens mode, with this version they are also disabled the "Documentation" and "Check for updates" menus.
PR created on behalf of the add-on author, with info provided by him (privately).
> Update Weather_Plus to 8.9

- get.php
- Name: Beep Keyboard
- Author: David CM
- Repo: https://github.com/davidacm/beepKeyboard
- Version: 1.8
- NVDA compatibility: 2018.3 and later
- Compatibility with NVDA 2022.1.
Submitting on behalf of @davidacm
> Beep Keyboard 1.8 (David ACM)

- get.php
- Name: Browser Nav
- Author: Tony Malykh
- Repo: https://github.com/mltony/nvda-browser-nav
- Version: 2.4
- NVDA compatibility: 2019.3 and later
From 1.15:
- Introduces bookmarks: QuickJump, QuickClick, SkipClutter and Hierarchical.
- Introduces optional ignoring focus events and muting live regions.
- Compatibility with NVDA 2022.
- Fixed QuickNav T command to jump to the first cell of the table.
- Bugfixes.
- Works better with Chrome v100
- Better warning messages.
- Improved certain use cases with MS Outlook
- Fixed broken option URLMatch.DOMAIN.
- Removed list and listItem from default configuration skipClutter item.
CC @mltony
> Browser Nav 2.4 (Tony Malykh)

- get.php
- Name (Example, Add-on Updater):  MathCAT
- Author (example, Your Name): Neil Soiffer
- Repo (example, https://github.com/yourname/addonName):  https://github.com/NSoiffer/MathCATForPython
- Version (example, 21.07): 0.1.14
- Update channel (example, stable, dev or stable and dev): stable
- NVDA compatibility (example, 2021.1 and beyond): 2018.1 and beyond
MathCAT is designed to eventually replace MathPlayer because MathPlayer is no longer supported. MathCAT generates speech and braille from MathML. The speech is enhanced with prosody so that it sounds more natural. The speech can be navigated in three modes using the same commands as MathPlayer. In addition, the navigation node is indicated on a braille display. Both Nemeth and UEB technical are supported.
MathCAT adds a settings menu …
> add 'mathcat' to the list

- get.php
- Name: Becky
- Author: Łukasz Golonka (@lukaszgo1)
- Repo: https://github.com/lukaszgo1/Becky/
- Version: 0.3-dev
- Update channel : dev
- NVDA compatibility: 2019.2 and beyond 
- Initial version available from the add-ons web site
Source code of the add-on has not been reviewed. I've asked for reviews [on add-ons list](https://nvda-addons.groups.io/g/nvda-addons/topic/91432033#18947)but since Becky! is quite esoteric piece of software it is likely  no other add-on developer except me is using it.
> Add development version of add-on for  Becky! Internet Mail

- get.php
- Name: Win Wizard
- Author: Oriol Gómez, current maintenance by Łukasz Golonka
- Repo: https://github.com/lukaszgo1/winWizard/
- Version: 5.0.4
- NVDA compatibility: 2019.3 and beyond
- Compatibility with NVDA 2022.1
- It is now possible to disable confirmation beeps in the add-ons settings panel
- Update translations
> Update winWizard to version 5.0.4

- get.php
- Name: NVDA Dev & Test Toolbox
- Author: Cyrille Bougot
- Repo: https://github.com/CyrilleB79/NVDA-Dev-Test-Toolbox
- Version: 2.1
- NVDA compatibility: 2019.2 and beyond
- Various bugfixes and code refactoring/cleaning to address all use cases: all supported versions, installed vs. run from source, etc. (contribution from Łukasz Golonka)
- Rewriting of the compa module (contribution from Łukasz Golonka)
- The restart dialog can now be opened only once.
- The object explorer shortcuts are now unassigned by default and need to be mapped by the user.
- With the object explorer, a double-press to call the script to report the current object's property now displays the reported information in a browseable message.
- New feature: Enhanced restart dialog to specify …
> New add-on: NVDA Dev & Test Toolbox (V2.1)

- get.php
- Version: 22.08
- NVDA compatibility: 2021.3 and later
- Sha256: 404e593c9b371a192d1d6581080fa01b97e82e34f3ff2098752cad3a1757cb03
- Added support for automatic add-on updates feature from Add-on Updater add-on. In particular, the add-on will not install if using unsupported Windows releases.
- Event debug log for events added by this add-on (drag complete, drag drop effect, drop target dropped) are logged from event handlers themselves rather than  through a dedicated method. This makes debug log for events more concise.
- Microsoft Solitaire Collection: In version 4.13 and later, NVDA will announce card (suit and rank) labels provided …
> Windows App Essentials 22.08

- get.php
- Version: 22.09
- Sha256: 1939d637e1526c209b06e0f84705dc0b704249184d353c1ce8c63629e6020ade
- NVDA 2022.2 or later is required, more so for security (2022.2.2 or later is recommended).
- Windows 10: Requires Version 21H2 or later.
- Various features and fixes that were included with the add-on are now part of NVDA. NVDA 2022.1 include support for Windows 11 Calculator, announcing history and memory items in Windows 10 Calculator, fixing inability to use arrow keys to review emojis in Windows 11 emoji panel, and resolving text output repetition in Windows Terminal 1.12.10733 and later. NVDA 2022.2 …
> Windows App Essentials 22.09

- get.php
- Version: 22.09.1
- Sha256: 42c3b79585e9cea9b067de1d23de01b2882adbbb7dc0e1fb455bf6f7e4fd6c4e
- Resolves drag and drop effect announcement repetitions in NVDA alpha snapshots. This will result in no focus announcement when drag and drop completes in some cases.
This release partially backports work done in development builds of the add-on. Focus announcement when drag completes is actually planned to be removed in the next stable (and a major) version of the add-on. This release also prepares to hand off drag and drop effect announcement to NVDA Core - ideally people should install the add-on …
> Windows App Essentials 22.09.1

- get.php
- Version: 22.10
- Sha256: d3eda5ab30776dab608ac6a29a6956086271a38b174dc86da0f155b63314690c
- The following UIA property changes are recognized: drag is grabbed (recognized as a distinct state), drop target effect.
- UIA drag start/cancel/complete events are recognized once again, this time as a state change events.
- NVDA will announce "dragging" when dragging certain items such as when arranging Windows 10 Start menu tiles by pressing Alt+Shift+arrow keys.
- Drop target dropped UIA event is removed. As a result, NVDA will no longer announce position of the newly dragged item by faking focus …
> Windows App Essentials 22.10

- get.php
- Name: Office Desk
- Author: Joseph Lee and others
- Repo: https://github.com/josephsl/officedesk
- Version: 22.10
- Sha256: dc728609ee600aa4adb1f61b2f2fd8cbdcd990c861d474304470f61e4c0134d8
- Initial release.
- In backstage view, NVDA will announce search count when search results appear, as well as announcing results when up 
- In Word, NVDA will no longer announce formatting changes such as bold and italic onoff multiple times.and down arrow keys are pressed.
- In Word Envelopes dialog, NVDA will announce edit field labels.
Office Desk is a new add-on designed to serve as a collaborative project to improve support for Microsoft (Office) 365 applications such as Word and Exce. This initial version includes the main Ofice …
> Office Desk 22.10 (initial version)

- get.php
- Name (Example, Add-on Updater): SMB
- Author (example, Your Name): Sao Mai Technology Team
- Repo (example, https://github.com/yourname/addonName): https://github.com/Sao-Mai-Center/SMB
- Version (example, 21.07): 22.8
- Update channel (example, stable, dev or stable and dev): stable
- NVDA compatibility (example, 2021.1 and beyond): 2019.3 and beyond):
- 2022.8: compatible with NVDA 2022.3
Sao Mai Braille (SMB) is a free rich text editing and Braille translation software for Windows, developed by [Sao Mai Center for the Blind](https://www.saomaicenter.org/en)
This is a small add-on to make NVDA screen reader more accessible to SMB's interface.
More info about this program can be found at <https://www.saomaicenter.org/en/smsoft/smb>
> SMB v 22.8 - Add-on for Sao Mai Braille program

- get.php
- Version: 22.12
- Sha256: f560fca6996455b576073d1c32a783a010415e37dc5ae149498fe2fcb56028dd
- Supported releases and builds across Windows 10 and 11 will be displayed if attempting to install the add-on on unsupported Windows releases including releases earlier than 10 and unsupported feature updates.
- Removed most of Windows version detection code from WinAppObjs global plugin as it was ineffective in preventing the add-on from running in unsupported Windows releases.
- Windows 11: If running on 22H2 beta builds (22622/22623), NVDA will recognize this fact and record this information in the log. …
> Windows App Essentials 22.12

- get.php
- Repo: not provided
- Version: 9.2
- Fixed bug when closing the weather report and details view window that crashed nvda.
- Fixed bug when closing the dialog after using the option View the output in a window.
Supersedes PR #437
> Update Weather_Plus to 9.2

- get.php
- Version: 23.01
- NVDA compatibility: 2022.3 and later
- Sha256: d8e3973faa32a375ad414ef911478919cfeb695841761824f6ac5e4fc0f3a742
- NVDA 2022.3 or later is required.
- Removed app module for People app.
- Removed the ability to toggle UIA notification announcements from apps such as Calculator via "Report notifications" setting found in NVDA's object presentation settings panel.
- In Windows 11 22H2 Moment 2, redesigned system tray overflow area can be detected properly when using mouse and/or touch interaction.
- NVDA will record processor architecture for the current Windows installation (x86/32-bit, AMD64, ARM64) in the log when the …
> Windows App Essentials 23.01

- get.php
- Version: 23.02
- NVDA compatibility: 2022.4 and later
- Sha256: e2c488464ac97b510aacfebfc2a3bbce5cd9f7b1e60c15e5cf487dae95e2156c
- NVDA 2022.4 or later is required.
- Various features and fixes that were included with the add-on are now part of NVDA. These include announcing "dragging" when an item is about to be dragged and announcing drag and drop target effects.
- Removed additional UIA event tracking facility as the last set of additional events (drag and drop) are included in NVDA 2022.4.
- Improved Windows 10 and 11 taskbar experience, including announcing results of rearranging icons when pressing Alt+Shift+left/right arrow …
> Windows App Essentials 23.02

- get.php
- Repo: Not provided
- Version: 9.4
- NVDA compatibility: 2017.3 and beyond (including 2023.1)
- Compatible with NVDA 2023.1
Requested on behalf of the author, who sent me the download link privately.
> Update Weather_Plus to 9.4

- get.php
- Name: Nuance Vocalizer 5.5 Driver
- Author: Tiflotecnia, LDA.
- Repo: https://github.com/ruifontes
- Version: 2.1.4
- NVDA compatibility: 2019.3 and beyond (including 2023.1)
- Renaming the internal name of synth from "vocalizer" to "vocalizerAutomotive" to allow coexistence with the CodeFactory add-on;
- Changing manifest.ini to be compatible with NVDA 2023.1;
- Introducing automatic update system.
[Announcement on add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/message/20297)
> Add Vocalizer Automotive 2.1.4

- get.php
- Name: Skype
- Author: Doug Lee
- Repo: Not provided
- Version: 2023.01.1
- NVDA compatibility: 2018.1 and beyond
- Compatible with NVDA 2023.1
[Announcement by Doug Lee on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/message/20258)
> Add Skype 2023.01.1

- readme.md
After merging this, archive this repository.
This repository will be archived to be replaced with [the addon store datastore repository](https://github.com/nvaccess/addon-datastore).
To submit add-ons, please [follow these instructions](https://github.com/nvaccess/addon-datastore/blob/master/README.md#submitting-an-add-on-version).
Add-ons in the new repository will still be made available via get.php and addons.nvda-project.org.
Existing add-ons in this repository will be migrated over.
> Archive addonFiles repo in favour of addon-datastore
